### ISSUE TITLE
[EngAut] CommandBot: Create GHA version

### ISSUE THREAD

**Issue by crystalin** [paritytech/command-bot#113]
**Background**:
- current command bot is fully dependent on GitLab, because it was designed to manage tasks queue via GitLab CI pipelines.
- if any parachain team would want to re-use this bot for their benchmarks and other tasks - the GHA+self-hosted runner is much simpler to set up than deploying a runtime NodeJS app with DB + self-hosted runners

**Stakeholders and Goals**:
- [Parity Internal]: unblock gitlab deprecation, as current implementation is locked-in for GitLab
- [Ecosystem] setup and run benchmarks easier

**Original request**:
We've been using the benchbot and are thinking to move to the command-bot, however we don't rely on gitlab for our CI.
Our current setup is using Github Action but with self-hosted instances (dedicated to building/testing).

I like the idea of the command-bot allowing commands from different sources (matrix/github/...) but it seems to be quite customized to how parity work (using gitlab, helm,...).

Do you have any plan on making it more generic to allow non-gitlab service ?

---

# [GitHub action milestone](https://github.com/paritytech/command-bot/milestone/1)

```[tasklist]
## Tasks
- [ ] https://github.com/paritytech/cmd-action/issues/4
- [ ] https://github.com/paritytech/cmd-action/issues/7
- [ ] https://github.com/paritytech/cmd-action/issues/10
- [ ] https://github.com/paritytech/cmd-action/issues/14
- [ ] https://github.com/paritytech/cmd-action/issues/12
- [ ] https://github.com/paritytech/cmd-action/issues/2
- [ ] https://github.com/paritytech/cmd-action/issues/20
- [ ] https://github.com/paritytech/cmd-action/issues/1
- [ ] https://github.com/paritytech/command-bot/issues/274
- [ ] https://github.com/paritytech/cmd-action/issues/22
- [x] Add a small action that reacts to `bot xyz` commands and sends a link to [the forum post](https://forum.polkadot.network/t/command-bot-has-migrated-to-github-actions/8722)
```

**Comment by mutantcornholio** [comment]
Could you elaborate on what currently doesn't work, or how `command-bot`'s way of spawning jobs contradicts your CI configuration?

**Comment by crystalin** [comment]
I didn't go as far a trying to setup everything yet. The documentation contains many element but it is a bit hard to know how all of the elements are orchestrated overall.
But in the setup part it mentions:
> Create a repository in GitLab and set up [GITLAB_PUSH_NAMESPACE](https://github.com/paritytech/command-bot/blob/master/.env.example.cjs) along with [GITLAB_ACCESS_TOKEN](https://github.com/paritytech/command-bot/blob/master/.env.example.cjs) to run the commands for the GitHub repository (Step 3).

That is why I supposed it required to do so, I'll try to set the bot up and see where I get stuck

**Comment by crystalin** [comment]
Also, the first line of readme also mention:
> command-bot executes arbitrary commands on GitLab CI

**Comment by mutantcornholio** [comment]
You're going through deployment/development setup. Are you trying to host your own instance?

**Comment by crystalin** [comment]
Ideally yes, but if you offer a service where we can plug our repo and our CI servers, I'm happy to try it (I don't think that would work in term of security however so we would end up hosting it)

**Comment by mutantcornholio** [comment]
Okay, I think I've misread the situation. Let us think on it.
Currently, it'll basically mean replacing at least half of the code, and that raises a big question on the vision of the project.

**Comment by mordamax** [comment]
@crystalin what kind of CI servers do you use?
I'm curious where would you like to run something like benchmarks

**Comment by mordamax** [comment]
@crystalin Currently, we defer the tasks to run and queue for the CI, in our case Gitlab. We are going to make it less opinionated and instead of creating a Gitlab CI job - create Kubernetes jobs.

What would be a desired infrastructure set up so you could deploy and use it on your side?

**Comment by crystalin** [comment]
Thank you, I think plugin it with github and using their GHA (self-hosted runner) is preferred but we could probably combine it with our kubernetes cluster too

**Comment by mordamax** [comment]
Current plan is to move away from gitlab completely, so will be porting the exiting command bot to separate repo, the idea is to set this up as Github action, with decoupled repo for command scripts and interface. 
https://github.com/paritytech/command-bot-scripts/tree/main/commands
This allows to avoid re-deploying/releasing the bot business logic from the commands implementation.

**Comment by Bullrich** [comment]
I will be taking up this task.

I have created a milestone to track this:

# [GitHub action milestone](https://github.com/paritytech/command-bot/milestone/1)

I have also created a bunch of small tasks to divide this job:

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/command-bot/issues/269
- [ ] https://github.com/paritytech/command-bot/issues/270
- [ ] https://github.com/paritytech/command-bot/issues/271
- [ ] https://github.com/paritytech/command-bot/issues/272
- [ ] https://github.com/paritytech/command-bot/issues/273
```

**Comment by Bullrich** [comment]
The repository [`cmd-action`](https://github.com/paritytech/cmd-action/) has been created. The action will be developed there.

I ran two experiments to see if this is feasible, both of them were succesfull:
- https://github.com/paritytech/cmd-action/pull/6
- https://github.com/paritytech-stg/polkadot-sdk/pull/26

**Comment by Bullrich** [comment]
Currently working on paritytech/cmd-action#1.

I'm making the system parse content from the comments and validating it with the commands.

**Comment by Bullrich** [comment]
Preparing schema handling.

I've been in contact with Oliver, our main stakeholder.
- We have decided that the repository will hold the required scripts (unless that a project evolves too much)
- Also, a similar action was commented by Basti: https://github.com/paritytech/command-bot-scripts/pull/69#discussion_r1548981688

The logic of configuration handling will be similar to review-bot's: Easy to read and hosted in the target repository.

`cmd-action` will be mainly a tool to "parse" commands and pass it to a github action with a repo script.

**Comment by Bullrich** [comment]
Currently working on https://github.com/paritytech/cmd-action/issues/7

Configuration files will be moved to be in `yaml` (can also be `toml`) so it's easier to read.

I'm preparing this ticket in combination with https://github.com/paritytech/cmd-action/issues/10 so we have a schema validator out of the box

**Comment by Bullrich** [comment]
# Completed the following tasks
  - https://github.com/paritytech/cmd-action/pull/7
  - https://github.com/paritytech/cmd-action/pull/10
    - https://github.com/paritytech/cmd-action/pull/11
  - https://github.com/paritytech/cmd-action/pull/12
    - https://github.com/paritytech/cmd-action/pull/15
  - https://github.com/paritytech/cmd-action/pull/14
    - https://github.com/paritytech/cmd-action/pull/17

**Comment by Bullrich** [comment]
## 22-26 of April

- https://github.com/paritytech/cmd-action/issues/12
  - https://github.com/paritytech/cmd-action/pull/15
- Currently working on https://github.com/paritytech/cmd-action/issues/2
  - Extract parameters from a command

**Comment by Bullrich** [comment]
Currently working on the finishing touches for https://github.com/paritytech/cmd-action/pull/18

This will close:
- paritytech/cmd-action#1
- paritytech/cmd-action#2

**Comment by Bullrich** [comment]
Closed:
- https://github.com/paritytech/cmd-action/issues/20
  - https://github.com/paritytech/cmd-action/issues/21

**Comment by Bullrich** [comment]
Completed last week:
- paritytech/cmd-action#22
  - paritytech/cmd-action#24
- paritytech/cmd-action#20
  - paritytech/cmd-action#21
- paritytech/cmd-action#25

**Comment by Bullrich** [comment]
Work in progress to migrate the command action to work as a github workflow:
- https://github.com/paritytech/polkadot-sdk/pull/4701

### Missing commands
- [ ] bench-all
- [ ] bench-overhead
- [ ] bench
- [x] fmt
- [ ] sample
- [ ] sync
- [x] update-ui

**Comment by Bullrich** [comment]
Finished preparing https://github.com/paritytech/polkadot-sdk/pull/4701

**Comment by Bullrich** [comment]
Completed migration of most commands:
- https://github.com/paritytech/polkadot-sdk/pull/4701

Currently working on adding the last command (sync): https://github.com/paritytech/polkadot-sdk/pull/4818
Blocked by https://github.com/paritytech/ci_cd/issues/995

**Comment by rzadp** [comment]
Note: I added a task to the list to:
- Add a small action that reacts to `bot xyz` commands and sends a link to [the forum post](https://forum.polkadot.network/t/command-bot-has-migrated-to-github-actions/8722).

**Comment by Bullrich** [comment]
> Note: I added a task to the list to:
> 
> * Add a small action that reacts to `bot xyz` commands and sends a link to [the forum post](https://forum.polkadot.network/t/command-bot-has-migrated-to-github-actions/8722).

paritytech/polkadot-sdk#5000 should provide the fix for this.

**Comment by mordamax** [comment]
Closing this as done in V1 and V2 versions -> 
- polkadot-sdk https://github.com/paritytech/product-engineering/issues/93
- runtimes https://github.com/polkadot-fellows/runtimes/pull/406

@crystalin we've gone with simple python script (could be short bash too, like [Astar does](https://github.com/AstarNetwork/Astar/blob/master/.github/workflows/benchmark.yml)) 
we didn't go with too complex generic (or runtime) solution as it's simple and could be adjusted per project needs
