### ISSUE TITLE
[EngAut] Prepare command-bot scripts to work in monorepo

### ISSUE THREAD

**Issue by mordamax** [paritytech/command-bot#174]
Prepare command-bot scripts to work in monorepo & runtimes in fellowship

Context:
- https://forum.parity.io/t/repo-reorg/1455/
- https://forum.parity.io/t/polkadot-1-0-release/1675/

### What's going to change
- polkadot & cumulus runtimes are moved to https://github.com/polkadot-fellows/runtimes
- polkadot/cumulus/substrate will be merged to one repository (something like polkadot-sdk)

### How will it impact command-bot?
Since the runtimes are moved out to fellowship org, as stated in [forum post](https://forum.parity.io/t/repo-reorg/1455/21), the only thing to test **try-runtime** and **benchmark** remains substrate `dev` pallet. So command-bot-scripts for substrate have to be updated to run it from polkadot-sdk considering the subfolder "substrate" from root of repo + the paths for weights
To simplify usage of command-bot scripts in monorepo, it's better to support "default arguments" which is only possible with named arguments (vs positioned that we have now). This leads also to a change of how we run the commands

| Current (Positioned) | New (Named) |
|--------|--------|
| bot bench $ runtime kusama pallet_name | bot bench polkadot-pallet --runtime=kusama --pallet=pallet_name |
| bot bench $ pallet dev pallet_name | bot bench substrate-pallet --pallet=pallet_name |
| bot bench $ xcm bridge-hub-kusama bridge-hubs pallet_name | bot bench cumulus-bridge-hubs --subcommand=xcm --runtime=bridge-hub-kusama --pallet=pallet_name |
| bot bench $ pallet asset-hub-polkadot assets pallet_balances | bot bench cumulus-assets --pallet=pallet_balances |
| bot bench $ pallet asset-hub-kusama assets pallet_balances | bot bench cumulus-assets --runtime=asset-hub-kusama --pallet=pallet_balances |
| bot try-runtime $ westend | bot try-runtime --chain=westend |
| bot try-runtime $ polkadot | bot try-runtime |
| bot fmt  | bot fmt | 

```[tasklist]
### Tasks
- [x] some https://github.com/paritytech/command-bot-scripts/ will have to be updated
- [x] install comman-bot-stg (https://github.com/organizations/paritytech-stg/settings/apps/command-bot-stg) to paritytech-stg/polkadot-sdk
- [x] Release & test on paritytech-stg
- [x] Release & test on paritytech
```

**Comment by mordamax** [comment]
Did quick pre-investigation and formed steps in description
