### ISSUE TITLE
[EngAut] CommandBot: new commands/features

### ISSUE THREAD

**Issue by mordamax** [paritytech/command-bot#209]
Commands:
```[tasklist]
### Tasks
- [ ] #100
- [ ] https://github.com/paritytech/command-bot/issues/211
- [ ] #177
- [ ] https://github.com/paritytech/command-bot/issues/59
- [ ] https://github.com/paritytech/command-bot/issues/237
- [ ] https://github.com/paritytech/command-bot/issues/262
- [ ] https://github.com/paritytech/command-bot/issues/263
- [ ] https://github.com/paritytech/command-bot/issues/167
```

**Comment by mordamax** [comment]
Weekly update:
- [x] https://github.com/paritytech/command-bot/issues/262
- [x] https://github.com/paritytech/command-bot/issues/263
- [x] https://github.com/paritytech/command-bot/issues/237

**Comment by mordamax** [comment]
Weekly update:
- Keep working on https://github.com/paritytech/command-bot/issues/167

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/parity-tech-update-for-february/6630/1
