### ISSUE TITLE
[EngAut] Command Bot - Q2'24

### ISSUE THREAD

**Issue by mordamax** [paritytech/command-bot#277]
Another batch of planned improvements for command-bot 
They do not conflict with the ongoing initiative to rewrite it as GH Action

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/command-bot/issues/279
- [ ] #275
- [ ] #274
- [ ] https://github.com/paritytech/command-bot/issues/278
- [ ] https://github.com/paritytech/command-bot/issues/280
- [ ] https://github.com/paritytech/command-bot-scripts/issues/71
```

**Comment by mordamax** [comment]
Fixed `bench-all substrate`. Apparently i was never tested, as rel eng team stopped to run those commands since polkadot 1.0

**Comment by mordamax** [comment]
No updates this week

**Comment by mordamax** [comment]
No updates this week, moving to `awaiting`
